// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaeHLm2ZvxFW5tFWw2U6PVef8bqgNMyjo',
    appId: '1:464390592820:web:6de855c27eb9fdbfd8ed61',
    messagingSenderId: '464390592820',
    projectId: 'fir-project-new-d38b1',
    authDomain: 'fir-project-new-d38b1.firebaseapp.com',
    storageBucket: 'fir-project-new-d38b1.appspot.com',
    measurementId: 'G-ZBW9ZFNVQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKc2wGP6VsF0HaVA1jAJzolnzeLpL78sc',
    appId: '1:464390592820:android:0bd3eb67d3aa38c2d8ed61',
    messagingSenderId: '464390592820',
    projectId: 'fir-project-new-d38b1',
    storageBucket: 'fir-project-new-d38b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU3g7Wm1DajePT7pcoIyiU808PYZe9uvQ',
    appId: '1:464390592820:ios:5e1e9fe574a03323d8ed61',
    messagingSenderId: '464390592820',
    projectId: 'fir-project-new-d38b1',
    storageBucket: 'fir-project-new-d38b1.appspot.com',
    iosBundleId: 'com.example.firebaseProjectNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU3g7Wm1DajePT7pcoIyiU808PYZe9uvQ',
    appId: '1:464390592820:ios:c5d210b249b6c63ad8ed61',
    messagingSenderId: '464390592820',
    projectId: 'fir-project-new-d38b1',
    storageBucket: 'fir-project-new-d38b1.appspot.com',
    iosBundleId: 'com.example.firebaseProjectNew.RunnerTests',
  );
}
